# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1998dllsDAsw3rHbcj2uPINpWVfaw-ttq
"""

# Script básico de calculadora em Python

# Solicita o primeiro número
num1 = float(input("Digite o primeiro número: "))

# Solicita o segundo número
num2 = float(input("Digite o segundo número: "))

# Solicita a operação desejada
operacao = input("Escolha a operação (+, -, *, /): ")

# Realiza o cálculo com base na operação
if operacao == '+':
    resultado = num1 + num2
elif operacao == '-':
    resultado = num1 - num2
elif operacao == '*':
    resultado = num1 * num2
elif operacao == '/':
    if num2 != 0:  # Verifica se não há divisão por zero
        resultado = num1 / num2
    else:
        print("Erro: Divisão por zero não é permitida.")
        exit(1)
else:
    print("Operação inválida.")
    exit(1)

# Exibe o resultado
print(f"O resultado de {num1} {operacao} {num2} é: {resultado}")